apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: product-service
build:
  artifacts:
    - image: product-service
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - kube/config.yaml
    - kube/postgres2.yaml
    - kube/deployment.yaml

