apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: development
spec:
  selector:
    app: order-service
  ports:
    - port: 8000
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-module
  namespace: development
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: order-service
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: order-config
          imagePullPolicy: IfNotPresent