apiVersion: v1
kind: PersistentVolume
metadata:
  name: api-gateway-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /home/ramin/Documents/nest_microservices/Restaurants_2/api-gateway
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: api-gateway-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi

      
